# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

knn_vote <- function(V, M, steps) {
    .Call(`_RareQ_knn_vote`, V, M, steps)
}

